package entidades;
// Generated 04/11/2016 16:56:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Contratos generated by hbm2java
 */
@Entity
@Table(name="contratos"
    ,catalog="contratosbd"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Referencia", "Ano"}) 
)
public class Contratos  implements java.io.Serializable {


     private Integer idContrato;
     private long referencia;
     private int ano;
     private String razao;
     private String identificador;
     private String endereco;
     private int agencia;
     private String objeto;
     private Date assinatura;
     private Date vencimento;
     private Date vigencia;
     private Set<Tarifas> tarifases = new HashSet<Tarifas>(0);
     private Set<Contas> contases = new HashSet<Contas>(0);
     private Set<Aditivos> aditivoses = new HashSet<Aditivos>(0);

    public Contratos() {
    }

	
    public Contratos(long referencia, int ano, String razao, String identificador, int agencia, String objeto, Date assinatura) {
        this.referencia = referencia;
        this.ano = ano;
        this.razao = razao;
        this.identificador = identificador;
        this.agencia = agencia;
        this.objeto = objeto;
        this.assinatura = assinatura;
    }
    public Contratos(long referencia, int ano, String razao, String identificador, String endereco, int agencia, String objeto, Date assinatura, Date vencimento, Date vigencia, Set<Tarifas> tarifases, Set<Contas> contases, Set<Aditivos> aditivoses) {
       this.referencia = referencia;
       this.ano = ano;
       this.razao = razao;
       this.identificador = identificador;
       this.endereco = endereco;
       this.agencia = agencia;
       this.objeto = objeto;
       this.assinatura = assinatura;
       this.vencimento = vencimento;
       this.vigencia = vigencia;
       this.tarifases = tarifases;
       this.contases = contases;
       this.aditivoses = aditivoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idContrato", unique=true, nullable=false)
    public Integer getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(Integer idContrato) {
        this.idContrato = idContrato;
    }

    
    @Column(name="Referencia", nullable=false)
    public long getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(long referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="Ano", nullable=false)
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }

    
    @Column(name="Razao", nullable=false, length=100)
    public String getRazao() {
        return this.razao;
    }
    
    public void setRazao(String razao) {
        this.razao = razao;
    }

    
    @Column(name="Identificador", nullable=false, length=14)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    
    @Column(name="Endereco", length=200)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="Agencia", nullable=false)
    public int getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(int agencia) {
        this.agencia = agencia;
    }

    
    @Column(name="Objeto", nullable=false, length=20)
    public String getObjeto() {
        return this.objeto;
    }
    
    public void setObjeto(String objeto) {
        this.objeto = objeto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Assinatura", nullable=false, length=10)
    public Date getAssinatura() {
        return this.assinatura;
    }
    
    public void setAssinatura(Date assinatura) {
        this.assinatura = assinatura;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Vencimento", length=10)
    public Date getVencimento() {
        return this.vencimento;
    }
    
    public void setVencimento(Date vencimento) {
        this.vencimento = vencimento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Vigencia", length=10)
    public Date getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contratos")
    public Set<Tarifas> getTarifases() {
        return this.tarifases;
    }
    
    public void setTarifases(Set<Tarifas> tarifases) {
        this.tarifases = tarifases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contratos")
    public Set<Contas> getContases() {
        return this.contases;
    }
    
    public void setContases(Set<Contas> contases) {
        this.contases = contases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contratos")
    public Set<Aditivos> getAditivoses() {
        return this.aditivoses;
    }
    
    public void setAditivoses(Set<Aditivos> aditivoses) {
        this.aditivoses = aditivoses;
    }




}


