package entidades;
// Generated 21/12/2016 12:36:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Objetos generated by hbm2java
 */
@Entity
@Table(name="objetos"
    ,catalog="contratosbd"
)
public class Objetos  implements java.io.Serializable {


     private String objeto;

    public Objetos() {
    }

    public Objetos(String objeto) {
       this.objeto = objeto;
    }
   
     @Id 

    
    @Column(name="Objeto", unique=true, nullable=false, length=45)
    public String getObjeto() {
        return this.objeto;
    }
    
    public void setObjeto(String objeto) {
        this.objeto = objeto;
    }




}


