/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controle.ControleObjetos;
import entidades.Objetos;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import utilidade.FiltroTexto;

/**
 *
 * @author amrsilva
 */
public class diagObjetos extends javax.swing.JDialog {
    ControleObjetos vCtrlObj = new ControleObjetos();
    informCadContratos formPai = null;
    diagDetalhes diagPai = null;
    /**
     * Creates new form diagObjetos
     * @param parent
     * @param modal
     * @param formPai
     */
    public diagObjetos(java.awt.Frame parent, boolean modal, informCadContratos formPai) {
        super(parent, modal);
        this.formPai = formPai;
        initComponents();
        lstObjetos.setBackground(Color.WHITE);
        atualizarLista();
    }
    
    public diagObjetos(java.awt.Frame parent, boolean modal, diagDetalhes formPai) {
        super(parent, modal);
        this.diagPai = formPai;
        initComponents();
        lstObjetos.setBackground(Color.WHITE);
        atualizarLista();
    }

    private void atualizarLista (){
        try {
            lstObjetos.removeAll();
            DefaultListModel vModelo = new DefaultListModel();
            for (Objetos contObj : vCtrlObj.ListarTodos()){
                vModelo.addElement((Object)contObj.getObjeto());
            }
            lstObjetos.setModel(vModelo);
            if (formPai != null) formPai.preencherCombo();
            if (diagPai != null) diagPai.preencherCombo();
        } catch (Exception ex) {
            Logger.getLogger(diagObjetos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstObjetos = new javax.swing.JList();
        btnIncluir = new javax.swing.JButton();
        txtObjeto = new javax.swing.JTextField();
        lblObjeto = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Objetos de Contratos");
        setResizable(false);

        lstObjetos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstObjetos);

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        ((AbstractDocument) txtObjeto.getDocument()).setDocumentFilter(new FiltroTexto(45));

        lblObjeto.setText("Objeto");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObjeto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObjeto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExcluir, btnIncluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblObjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        try {
            Objetos vObj = new Objetos(txtObjeto.getText());
            vCtrlObj.Incluir(vObj);
            txtObjeto.setText("");
            if (formPai != null) formPai.preencherCombo();
            if (diagPai != null) diagPai.preencherCombo();
            atualizarLista();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao incluir objeto\n" + ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:try {
        try{
            if (lstObjetos.getSelectedIndex()!=-1){
                System.out.println("a");
                vCtrlObj.Excluir(vCtrlObj.ListarTodos().get(lstObjetos.getSelectedIndex()));
                atualizarLista();
            } else JOptionPane.showMessageDialog(this, "Selecione um Objeto", "Erro!", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao incluir objeto\n" + ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblObjeto;
    private javax.swing.JList<String> lstObjetos;
    private javax.swing.JTextField txtObjeto;
    // End of variables declaration//GEN-END:variables
}
