/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controle.ControleContas;
import entidades.Contratos;
import entidades.Contas;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amrsilva
 */
public class diagContas extends javax.swing.JDialog {
    Contratos Pai;
    ControleContas vCtrlContas = new ControleContas();
    private List<Contas> vListaCont;
    /**
     * Creates new form diagContas
     * @param parent
     * @param modal
     * @param Pai
     */
    public diagContas(java.awt.Frame parent, boolean modal, Contratos Pai) {
        super(parent, modal);
        initComponents();
        this.Pai = Pai;
        atualizarTabela();
    }
    
    private void atualizarTabela(){
        DecimalFormat dfC = new DecimalFormat("0000000000");
        DecimalFormat dfA = new DecimalFormat("0000");
        
        try {
            vListaCont = vCtrlContas.ListarTodos(Pai);
        } catch (Exception ex) {
            Logger.getLogger(informConContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel vModelo = (DefaultTableModel) tblContas.getModel();
        vModelo.setNumRows(0);
        for(Contas contConta : vListaCont) {
            vModelo.addRow(new String[3]);
            vModelo.setValueAt(dfC.format(contConta.getNumero()), vModelo.getRowCount()-1, 2);
            vModelo.setValueAt(dfA.format(contConta.getAgencia()), vModelo.getRowCount()-1, 1);
            vModelo.setValueAt(contConta.getDescricao(), vModelo.getRowCount()-1, 0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        btnAdcionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        ftfNumero = new javax.swing.JFormattedTextField();
        lblDescricao = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        ftfAgencia = new javax.swing.JFormattedTextField();
        lblAgencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Agência", "Número"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContas);
        if (tblContas.getColumnModel().getColumnCount() > 0) {
            tblContas.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblContas.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        btnAdcionar.setText("Adicionar");
        btnAdcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcionarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        try {
            ftfNumero.setFocusLostBehavior(3);
            ftfNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblDescricao.setText("Descrição");

        lblNumero.setText("Número");

        try {
            ftfAgencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblAgencia.setText("Agência");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricao)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgencia)
                                    .addComponent(ftfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumero)
                                    .addComponent(ftfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnAdcionar)
                                .addGap(84, 84, 84)
                                .addComponent(btnExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdcionar, btnAlterar, btnExcluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnAdcionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarActionPerformed
        // TODO add your handling code here:
        if (txtDescricao.getText().trim().equals("") || ftfAgencia.getText().trim().equals("") || ftfNumero.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Contas vConta = new Contas(Pai, txtDescricao.getText().trim(), Integer.parseInt(ftfAgencia.getText().trim()),
                    Integer.parseInt(ftfNumero.getText().trim()));
            vCtrlContas.Incluir(vConta);
            txtDescricao.setText("");
            ftfNumero.setValue(null);
            ftfNumero.setText("");
            ftfAgencia.setValue(null);
            ftfAgencia.setText("");
            atualizarTabela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao incluir Conta\n" + ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdcionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        try {
            for (int i = 0; i < tblContas.getRowCount(); i++) {
                vListaCont.get(i).setDescricao(tblContas.getValueAt(i, 0).toString());
                vListaCont.get(i).setAgencia(Integer.parseInt(tblContas.getValueAt(i, 1).toString()));
                vListaCont.get(i).setNumero(Integer.parseInt(tblContas.getValueAt(i, 1).toString()));
                vCtrlContas.Alterar(vListaCont.get(i));
            }
            atualizarTabela();
            JOptionPane.showMessageDialog(this, "Contas alteradas com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao alterar Conta:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }                                         
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (tblContas.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Selecione uma conta", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Confirma a exclusão desta Conta?", "Confirmação", JOptionPane.YES_NO_OPTION) == 
            JOptionPane.YES_OPTION){
            try {
                vCtrlContas.Excluir(vListaCont.get(tblContas.getSelectedRow()));
                atualizarTabela();
                JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir Conta:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdcionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JFormattedTextField ftfAgencia;
    private javax.swing.JFormattedTextField ftfNumero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTable tblContas;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
