/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controle.ControleTarifas;
import entidades.Contratos;
import entidades.Tarifas;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amrsilva
 */
public class diagTarifas extends javax.swing.JDialog {
    Contratos Pai;
    ControleTarifas vCtrlTarifas = new ControleTarifas();
    private List<Tarifas> vListaTarif;
    /**
     * Creates new form diagTarifas
     * @param parent
     * @param modal
     * @param Pai
     */
    public diagTarifas(java.awt.Frame parent, boolean modal, Contratos Pai) {
        super(parent, modal);
        initComponents();
        this.Pai = Pai;
        atualizarTabela();
    }
    
    private void atualizarTabela(){
        DecimalFormat df = new DecimalFormat("#,##0.00");
        try {
            vListaTarif = Pai.getTarifases();//vCtrlTarifas.ListarTodos(Pai);
        } catch (Exception ex) {
            Logger.getLogger(informConContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel vModelo = (DefaultTableModel) tblTarifas.getModel();
        vModelo.setNumRows(0);
        for(Tarifas contTarif : vListaTarif) {
            vModelo.addRow(new String[2]);
            vModelo.setValueAt(df.format(contTarif.getValor()), vModelo.getRowCount()-1, 1);
            vModelo.setValueAt(contTarif.getDescricao(), vModelo.getRowCount()-1, 0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarifas = new javax.swing.JTable();
        btnAdcionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        ftfValor = new javax.swing.JFormattedTextField();
        lblDescricao = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tblTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Valor (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTarifas);
        if (tblTarifas.getColumnModel().getColumnCount() > 0) {
            tblTarifas.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        btnAdcionar.setText("Adicionar");
        btnAdcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcionarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        ftfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        lblDescricao.setText("Descrição");

        lblValor.setText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdcionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescricao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor)
                            .addComponent(ftfValor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdcionar, btnAlterar, btnExcluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(lblValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnAdcionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarActionPerformed
        // TODO add your handling code here:
        try {
            Tarifas vTarifa = new Tarifas(Pai, txtDescricao.getText(), new BigDecimal(ftfValor.getValue().toString()));
            vCtrlTarifas.Incluir(vTarifa);
            txtDescricao.setText("");
            ftfValor.setValue(null);
            txtDescricao.setText("");
            atualizarTabela();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao incluir Tarifa\n" + ex, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdcionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        try {
            for (int i = 0; i < tblTarifas.getRowCount(); i++) {
                vListaTarif.get(i).setDescricao(tblTarifas.getValueAt(i, 0).toString());
                vListaTarif.get(i).setValor(new BigDecimal(tblTarifas.getValueAt(i, 1).toString().replace(".", "").replace(",", ".")));
                vCtrlTarifas.Alterar(vListaTarif.get(i));
            }
            atualizarTabela();
            JOptionPane.showMessageDialog(this, "Tarifas alteradas com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao alterar Tarifa:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }                                         
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Confirma a exclusão desta Tarifa?", "Confirmação", JOptionPane.YES_NO_OPTION) == 
                JOptionPane.YES_OPTION){
            if (tblTarifas.getSelectedRow() != -1){
                try {
                    vCtrlTarifas.Excluir(vListaTarif.get(tblTarifas.getSelectedRow()));
                    atualizarTabela();
                    JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir Tarifa:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else JOptionPane.showMessageDialog(this, "Selecione um Tarifa.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdcionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JFormattedTextField ftfValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tblTarifas;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
