/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utilidade.ConfigUtil;

/**
 *
 * @author amrsilva
 */

public class formPrincipal extends javax.swing.JFrame {
    ConfigUtil configUtil = new ConfigUtil();
    informCadContratos informCadContratosIns = new informCadContratos();
    informConContrato informConsultaIns = new informConContrato();
    public static final String SERVIDOR = "Suret_Geseb_009";
    public static final String USUARIO = "root";
    public static final String SENHA = "1234";
    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnPrincipal = new javax.swing.JDesktopPane();
        mnbPrincipal = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mniCadContrato = new javax.swing.JMenuItem();
        mniConContrato = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniConifgEmail = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Contratos");
        setExtendedState(6);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/imagens/Icone.png")));

        dpnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout dpnPrincipalLayout = new javax.swing.GroupLayout(dpnPrincipal);
        dpnPrincipal.setLayout(dpnPrincipalLayout);
        dpnPrincipalLayout.setHorizontalGroup(
            dpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        dpnPrincipalLayout.setVerticalGroup(
            dpnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        mnuCadastro.setText("Contratos");

        mniCadContrato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mniCadContrato.setText("Inclusão");
        mniCadContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadContratoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mniCadContrato);

        mniConContrato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mniConContrato.setText("Consulta");
        mniConContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConContratoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mniConContrato);
        mnuCadastro.add(jSeparator1);

        mniConifgEmail.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mniConifgEmail.setText("Configurar e-mail");
        mniConifgEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConifgEmailActionPerformed(evt);
            }
        });
        mnuCadastro.add(mniConifgEmail);

        mnbPrincipal.add(mnuCadastro);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadContratoActionPerformed
        // TODO add your handling code here:
        if (informCadContratosIns == null || !informCadContratosIns.isVisible()){
            dpnPrincipal.remove(informCadContratosIns);
            informCadContratosIns = new informCadContratos();
            dpnPrincipal.add(informCadContratosIns);
            informCadContratosIns.setLocation((dpnPrincipal.getWidth() - informCadContratosIns.getWidth()) / 2,
                    (dpnPrincipal.getHeight()- informCadContratosIns.getHeight()) / 2);
            informCadContratosIns.setVisible(true);
        } else {
            informCadContratosIns.moveToFront();
            try {
                informCadContratosIns.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
        }
    }//GEN-LAST:event_mniCadContratoActionPerformed

    private void mniConContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConContratoActionPerformed
        // TODO add your handling code here:
        if (informConsultaIns == null || !informConsultaIns.isVisible()){
            dpnPrincipal.remove(informConsultaIns);
            informConsultaIns = new informConContrato();
            dpnPrincipal.add(informConsultaIns);
            informConsultaIns.setLocation((dpnPrincipal.getWidth() - informConsultaIns.getWidth()) / 2,
                    (dpnPrincipal.getHeight()- informConsultaIns.getHeight()) / 2);
            informConsultaIns.setVisible(true);
        } else {
            informConsultaIns.moveToFront();
            try {
                informConsultaIns.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_mniConContratoActionPerformed

    private void mniConifgEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConifgEmailActionPerformed
        // TODO add your handling code here:
        diagConfigEmail dialog = new diagConfigEmail(this, true, configUtil);
        dialog.setVisible(true);
    }//GEN-LAST:event_mniConifgEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenuItem mniCadContrato;
    private javax.swing.JMenuItem mniConContrato;
    private javax.swing.JMenuItem mniConifgEmail;
    private javax.swing.JMenu mnuCadastro;
    // End of variables declaration//GEN-END:variables
}
