/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controle.ControleContratos;
import controle.ControleObjetos;
import entidades.Contratos;
import entidades.Objetos;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import utilidade.ConfigUtil;
import utilidade.EmailUtil;
import utilidade.Relatorios;
import utilidade.Validadores;


/**
 *
 * @author amrsilva
 */
public class informConContrato extends javax.swing.JInternalFrame {
    
    private List<Contratos> vListaContr;
    ControleContratos vCtrlContratos = new ControleContratos();
    Integer[] vIdFiltro = new Integer[]{};
    
    /**
     * Creates new form informConsulta
     */
    public informConContrato() {
        initComponents();
        tblContratos.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        preencherCombo();
        atualizarTabela(false);
        try {
            ftfDataInicio.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##/##/####")));
            ftfDataFinal.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##/##/####")));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro com a JVM.\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpbCPFCNPJ = new javax.swing.ButtonGroup();
        gpbDatas = new javax.swing.ButtonGroup();
        panConContratos = new javax.swing.JPanel();
        txtRazao = new javax.swing.JTextField();
        lblRazao = new javax.swing.JLabel();
        lblReferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        lblAgencia = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        ftfCPFCNPJ = new javax.swing.JFormattedTextField();
        rbtCPF = new javax.swing.JRadioButton();
        rbtCNPJ = new javax.swing.JRadioButton();
        btnDetalhes = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        ftfDataInicio = new javax.swing.JFormattedTextField();
        ftfDataFinal = new javax.swing.JFormattedTextField();
        lblDataInicial = new javax.swing.JLabel();
        lblDataFinal = new javax.swing.JLabel();
        rbtAssinatura = new javax.swing.JRadioButton();
        rbtVigencia = new javax.swing.JRadioButton();
        btnImprimir = new javax.swing.JButton();
        btnTarifas = new javax.swing.JButton();
        btnVencidos = new javax.swing.JButton();
        btnEmail = new javax.swing.JButton();
        btaIndeterminado = new javax.swing.JToggleButton();
        lblObjeto = new javax.swing.JLabel();
        cbxObjeto = new javax.swing.JComboBox();
        txtAno = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        scpContratos = new javax.swing.JScrollPane();
        tblContratos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Contratos");
        setName(""); // NOI18N

        panConContratos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panConContratos.setToolTipText("Itens de pesquisa");
        panConContratos.setFocusCycleRoot(true);
        panConContratos.setNextFocusableComponent(txtReferencia);

        txtRazao.setNextFocusableComponent(ftfDataInicio);

        lblRazao.setText("Razão Social / Nome:");

        lblReferencia.setText("Número");

        txtReferencia.setFocusCycleRoot(true);
        txtReferencia.setNextFocusableComponent(txtAno);

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        lblAgencia.setText("Agência");

        txtAgencia.setNextFocusableComponent(cbxObjeto);

        btnLimpar.setText("Limpar Filtro");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        try {
            ftfCPFCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCPFCNPJ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfCPFCNPJ.setNextFocusableComponent(txtAgencia);

        gpbCPFCNPJ.add(rbtCPF);
        rbtCPF.setText("CPF");
        rbtCPF.setNextFocusableComponent(ftfCPFCNPJ);
        rbtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCPFActionPerformed(evt);
            }
        });

        gpbCPFCNPJ.add(rbtCNPJ);
        rbtCNPJ.setSelected(true);
        rbtCNPJ.setText("CNPJ");
        rbtCNPJ.setNextFocusableComponent(rbtCPF);
        rbtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCNPJActionPerformed(evt);
            }
        });

        btnDetalhes.setText("Detalhes");
        btnDetalhes.setNextFocusableComponent(btnExcluir);
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir Contrato");
        btnExcluir.setNextFocusableComponent(btnTarifas);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        ftfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfDataInicio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfDataInicio.setNextFocusableComponent(ftfDataFinal);

        ftfDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfDataFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ftfDataFinal.setNextFocusableComponent(rbtVigencia);

        lblDataInicial.setText("Início do período");

        lblDataFinal.setText("Fim do período");

        gpbDatas.add(rbtAssinatura);
        rbtAssinatura.setText("Assinatura");
        rbtAssinatura.setNextFocusableComponent(btaIndeterminado);
        rbtAssinatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAssinaturaActionPerformed(evt);
            }
        });

        gpbDatas.add(rbtVigencia);
        rbtVigencia.setSelected(true);
        rbtVigencia.setText("Vigência");
        rbtVigencia.setName("true"); // NOI18N
        rbtVigencia.setNextFocusableComponent(rbtAssinatura);
        rbtVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtVigenciaActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir Analítico");
        btnImprimir.setNextFocusableComponent(btnEmail);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnTarifas.setText("Tarifas");
        btnTarifas.setNextFocusableComponent(btnImprimir);
        btnTarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarifasActionPerformed(evt);
            }
        });

        btnVencidos.setText("Prestes a vencer");
        btnVencidos.setNextFocusableComponent(tblContratos);
        btnVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVencidosActionPerformed(evt);
            }
        });

        btnEmail.setText("Enviar e-mail");
        btnEmail.setNextFocusableComponent(btnVencidos);
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });

        btaIndeterminado.setText("Vigência Indeterminada");
        btaIndeterminado.setName("false"); // NOI18N
        btaIndeterminado.setNextFocusableComponent(btnFiltrar);

        lblObjeto.setText("Objeto");

        cbxObjeto.setNextFocusableComponent(txtRazao);

        txtAno.setNextFocusableComponent(rbtCNPJ);

        lblAno.setText("Ano");

        javax.swing.GroupLayout panConContratosLayout = new javax.swing.GroupLayout(panConContratos);
        panConContratos.setLayout(panConContratosLayout);
        panConContratosLayout.setHorizontalGroup(
            panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConContratosLayout.createSequentialGroup()
                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panConContratosLayout.createSequentialGroup()
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataInicial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panConContratosLayout.createSequentialGroup()
                                .addComponent(rbtVigencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtAssinatura))
                            .addComponent(btaIndeterminado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panConContratosLayout.createSequentialGroup()
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRazao)
                            .addGroup(panConContratosLayout.createSequentialGroup()
                                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReferencia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAno)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panConContratosLayout.createSequentialGroup()
                                .addComponent(rbtCNPJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtCPF))
                            .addComponent(ftfCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgencia)
                            .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObjeto)
                            .addComponent(cbxObjeto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConContratosLayout.createSequentialGroup()
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDetalhes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFiltrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panConContratosLayout.createSequentialGroup()
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVencidos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panConContratosLayout.setVerticalGroup(
            panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConContratosLayout.createSequentialGroup()
                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConContratosLayout.createSequentialGroup()
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFiltrar)
                            .addComponent(btnLimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDetalhes)
                            .addComponent(btnExcluir))
                        .addGap(6, 6, 6))
                    .addGroup(panConContratosLayout.createSequentialGroup()
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panConContratosLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblReferencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConContratosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConContratosLayout.createSequentialGroup()
                                        .addComponent(lblAno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConContratosLayout.createSequentialGroup()
                                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblAgencia)
                                            .addComponent(lblObjeto))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConContratosLayout.createSequentialGroup()
                                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rbtCPF)
                                            .addComponent(rbtCNPJ))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ftfCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRazao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panConContratosLayout.createSequentialGroup()
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImprimir))
                        .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panConContratosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDataFinal)
                                        .addComponent(lblDataInicial))
                                    .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rbtVigencia)
                                        .addComponent(rbtAssinatura)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panConContratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ftfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btaIndeterminado))
                                .addGap(22, 22, 22))
                            .addGroup(panConContratosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnVencidos)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panConContratosLayout.createSequentialGroup()
                        .addComponent(btnTarifas)
                        .addGap(6, 6, 6)
                        .addComponent(btnEmail)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tblContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ag.", "Número", "Ano", "Razão Social / Nome", "CNPJ/CPF", "Objeto", "Assinatura", "Vigência"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContratos.setNextFocusableComponent(txtReferencia);
        tblContratos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scpContratos.setViewportView(tblContratos);
        if (tblContratos.getColumnModel().getColumnCount() > 0) {
            tblContratos.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblContratos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblContratos.getColumnModel().getColumn(3).setMinWidth(350);
            tblContratos.getColumnModel().getColumn(3).setPreferredWidth(500);
            tblContratos.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblContratos.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblContratos.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblContratos.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpContratos)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panConContratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panConContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpContratos, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailActionPerformed
        // TODO add your handling code here:
        String toAddress;
        String subject = "Contratos Vencidos";
        String message;

        File[] attachFiles;

        File selectedFile = new File("Contratos.pdf");
        attachFiles = new File[] {selectedFile};

        try {
            ConfigUtil configUtil = new ConfigUtil();
            Properties smtpProperties = configUtil.loadConfigProperties();
            Properties messageProperties = configUtil.loadMailProperties();
            message = messageProperties.getProperty("mail.message");
            toAddress = messageProperties.getProperty("mail.addressee");
            EmailUtil.sendEmail(smtpProperties, toAddress.trim(), subject, message, attachFiles);
            JOptionPane.showMessageDialog(this, "E-mail enviado com sucesso!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao enviar e-mail: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEmailActionPerformed

    private void btnVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVencidosActionPerformed
        try {
            // TODO add your handling code here:
            Relatorios Relat = new Relatorios();
            Integer[] vIdFiltroTemp;
            List<Contratos> vListaContrTemp;
            vListaContrTemp = vCtrlContratos.ListarVencidos();
            if (vListaContrTemp != null && vListaContrTemp.size() > 0){
                vIdFiltroTemp = new Integer[vListaContrTemp.size()];
                System.out.println(vListaContrTemp.size());
                for (int i = 0; i < vListaContrTemp.size(); i++) {
                    vIdFiltroTemp[i] = vListaContrTemp.get(i).getIdContrato();
                }
                Relat.runReport("filtro", vIdFiltroTemp);
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum contrato prestes a vencer encontrado",
                    "Controle Contratos", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(informConContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVencidosActionPerformed

    private void btnTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarifasActionPerformed
        // TODO add your handling code here:
        if (tblContratos.getSelectedRow()!=-1) {
            diagTarifas diagTarifasInstancia = new diagTarifas(null, true, vListaContr.get(tblContratos.getSelectedRow()));
            diagTarifasInstancia.setTitle(vListaContr.get(tblContratos.getSelectedRow()).getRazao());
            diagTarifasInstancia.setVisible(true);
        } else JOptionPane.showMessageDialog(this, "Selecione um contrato.");
    }//GEN-LAST:event_btnTarifasActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        Relatorios Relat = new Relatorios();
        try {
            Relat.runReport("filtro", vIdFiltro);
        } catch (Exception ex) {
            Logger.getLogger(diagDetalhes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void rbtVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtVigenciaActionPerformed
        // TODO add your handling code here:
        if (rbtVigencia.isSelected()) btaIndeterminado.setEnabled(true);
        else btaIndeterminado.setEnabled(false);btaIndeterminado.setName("false");
    }//GEN-LAST:event_rbtVigenciaActionPerformed

    private void rbtAssinaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAssinaturaActionPerformed
        // TODO add your handling code here:
        if (!rbtVigencia.isSelected()){
            btaIndeterminado.setSelected(false);
            btaIndeterminado.setEnabled(false);
            ftfDataFinal.setEnabled(true);
        } else btaIndeterminado.setEnabled(true);
    }//GEN-LAST:event_rbtAssinaturaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Confirma a exclusão do contrato?\nTodas as tarifas e aditivos serão perdidos.",
            "Excluir", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
        if (tblContratos.getSelectedRow() != -1){
            try {
                vCtrlContratos.Excluir(vListaContr.get(tblContratos.getSelectedRow()));
                atualizarTabela(false);
                JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso.", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir aditivo:\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else JOptionPane.showMessageDialog(this, "Selecione um aditivo.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        // TODO add your handling code here:
        if (tblContratos.getSelectedRow()!=-1) {
            diagDetalhes diagDetalhesInstancia = new diagDetalhes(null, true, vListaContr.get(tblContratos.getSelectedRow()));
            diagDetalhesInstancia.setTitle(vListaContr.get(tblContratos.getSelectedRow()).getRazao());
            diagDetalhesInstancia.setVisible(true);
            vCtrlContratos = new ControleContratos();
            atualizarTabela(false);
            preencherCombo();
        } else JOptionPane.showMessageDialog(this, "Selecione um contrato.");

    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void rbtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCNPJActionPerformed
        // TODO add your handling code here:
        try {
            final MaskFormatter mfCNPJ = new MaskFormatter("##.###.###/####-##");
            ftfCPFCNPJ.setText("");
            ftfCPFCNPJ.setValue(null);
            if (evt.getActionCommand().equals("CNPJ")){
                ftfCPFCNPJ.setFormatterFactory(new DefaultFormatterFactory(mfCNPJ));
            }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro com a JVM." + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbtCNPJActionPerformed

    private void rbtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCPFActionPerformed
        // TODO add your handling code here:
        try {
            final MaskFormatter mfCPF = new MaskFormatter("###.###.###-##");
            ftfCPFCNPJ.setText("");
            ftfCPFCNPJ.setValue(null);
            if (evt.getActionCommand().equals("CPF")) ftfCPFCNPJ.setFormatterFactory(new DefaultFormatterFactory(mfCPF));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro com a JVM." + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbtCPFActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        atualizarTabela(false);
        vCtrlContratos.Backup();
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        if (!criarFiltro()) JOptionPane.showMessageDialog(this, "Preencha algum campo.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btaIndeterminado;
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnEmail;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnTarifas;
    private javax.swing.JButton btnVencidos;
    private javax.swing.JComboBox cbxObjeto;
    private javax.swing.JFormattedTextField ftfCPFCNPJ;
    private javax.swing.JFormattedTextField ftfDataFinal;
    private javax.swing.JFormattedTextField ftfDataInicio;
    private javax.swing.ButtonGroup gpbCPFCNPJ;
    private javax.swing.ButtonGroup gpbDatas;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblDataFinal;
    private javax.swing.JLabel lblDataInicial;
    private javax.swing.JLabel lblObjeto;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JPanel panConContratos;
    private javax.swing.JRadioButton rbtAssinatura;
    private javax.swing.JRadioButton rbtCNPJ;
    private javax.swing.JRadioButton rbtCPF;
    private javax.swing.JRadioButton rbtVigencia;
    private javax.swing.JScrollPane scpContratos;
    private javax.swing.JTable tblContratos;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JTextField txtReferencia;
    // End of variables declaration//GEN-END:variables

    private void atualizarNomes(){
        if (rbtVigencia.isSelected()) rbtVigencia.setName("true");
        else rbtVigencia.setName("false");
        if (btaIndeterminado.isSelected()) btaIndeterminado.setName("true");
        else btaIndeterminado.setName("false");
    }
    
    public void preencherCombo(){
        try {
            cbxObjeto.removeAll();
            DefaultComboBoxModel vModelo = new DefaultComboBoxModel();
            for (Objetos contObj : new ControleObjetos().ListarTodos()){
                vModelo.addElement((Object)contObj.getObjeto());
            }
            cbxObjeto.setModel(vModelo);
            cbxObjeto.setSelectedIndex(-1);
            cbxObjeto.setSelectedItem("");
        } catch (Exception ex) {
            Logger.getLogger(diagObjetos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void atualizarTabela(boolean Filtro){
        if (!Filtro){
            try {
                String[] Dados = {"", "", "", "", "", "", "", "", "", ""};
                vListaContr = vCtrlContratos.ListarComMultiplosFiltros(Dados);
                vIdFiltro = new Integer[]{};
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao acessar o banco de dados.\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        DefaultTableModel vModelo = (DefaultTableModel) tblContratos.getModel();
        vModelo.setNumRows(0);
        for(Contratos contContr : vListaContr) {
            String vIdentificador = contContr.getIdentificador();
            if (contContr.getIdentificador()!= null){
                boolean vCNPJ = Validadores.isCNPJ("00000000000000".substring(contContr.getIdentificador().length())
                            + contContr.getIdentificador());
                boolean vCPF = false;
                if (contContr.getIdentificador().length() <= 11 && !vCNPJ) vCPF = Validadores.isCPF("00000000000".substring(
                        contContr.getIdentificador().length()) + contContr.getIdentificador());
                try {
                    if (vCNPJ) {
                    MaskFormatter mfCNPJ  = new MaskFormatter("##.###.###/####-##");
                    mfCNPJ.setValueContainsLiteralCharacters(false);
                    vIdentificador = mfCNPJ.valueToString("00000000000000".substring(contContr.getIdentificador().length())
                            + contContr.getIdentificador());
                    } else if (vCPF){
                        final MaskFormatter mfCPF  = new MaskFormatter("###.###.###-##");
                        mfCPF.setValueContainsLiteralCharacters(false);
                        vIdentificador = mfCPF.valueToString("00000000000".substring(contContr.getIdentificador().length())
                                + contContr.getIdentificador());
                    }
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Erro ao ler CPF/CNPJ no banco de dados.\n" + ex, "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
            vModelo.addRow(new String[5]);
            if (contContr.getAgencia()!= 0) vModelo.setValueAt("0000".substring(String.valueOf(contContr.getAgencia()).length()) 
                    + String.valueOf(contContr.getAgencia()), vModelo.getRowCount()-1, 0);
            vModelo.setValueAt(contContr.getAno(), vModelo.getRowCount()-1, 2);
            vModelo.setValueAt(contContr.getRazao(), vModelo.getRowCount()-1, 3);
            vModelo.setValueAt(vIdentificador, vModelo.getRowCount()-1, 4);
            vModelo.setValueAt(contContr.getReferencia(), vModelo.getRowCount()-1, 1);
            vModelo.setValueAt(contContr.getObjeto(), vModelo.getRowCount()-1, 5);
            vModelo.setValueAt(new SimpleDateFormat("dd/MM/yyyy").format(contContr.getAssinatura()), vModelo.getRowCount()-1, 6);
            if (contContr.getVigencia()!= null && !contContr.getVigencia().toString().trim().equals(""))
                vModelo.setValueAt(new SimpleDateFormat("dd/MM/yyyy").format(contContr.getVigencia()), vModelo.getRowCount()-1, 7);
            else vModelo.setValueAt("Indefinido",vModelo.getRowCount()-1, 7);
        }
    }
    
    private void limparCampos (){
        txtAgencia.setText("");
        ftfCPFCNPJ.setText("");
        ftfCPFCNPJ.setValue(null);
        txtReferencia.setText("");
        txtRazao.setText("");
        ftfDataFinal.setText("");
        ftfDataFinal.setValue(null);
        ftfDataInicio.setText("");
        ftfDataInicio.setValue(null);
        cbxObjeto.setSelectedIndex(-1);
        cbxObjeto.setSelectedItem("");
    }
    
    private boolean criarFiltro (){
        boolean Ret;
        if (!txtReferencia.getText().trim().equals("")) Ret = true;
        else if (!txtAno.getText().trim().equals("")) Ret = true;
        else if (!ftfCPFCNPJ.getText().replaceAll("\\D", "").trim().equals("")) Ret = true;
        else if (!txtAgencia.getText().equals("")) Ret = true;
        else if (!txtRazao.getText().trim().equals("")) Ret = true;
        else if (cbxObjeto.getSelectedIndex()>=0) Ret = true;
        else if (!ftfDataInicio.getText().trim().equals("/  /")) Ret = true;
        else Ret = !ftfDataFinal.getText().trim().equals("/  /");
        if (Ret){
            atualizarNomes();
            String DtI = "", DtF = "", Identifi = "", Obj = "";
            if (!ftfDataInicio.getText().trim().equals("/  /") || !(ftfDataInicio.getValue() == null))
                        DtI = (new SimpleDateFormat("yyyy-MM-dd").format(new Date(
                        Integer.parseInt(ftfDataInicio.getText().substring(6,10))-1900,
                        Integer.parseInt(ftfDataInicio.getText().substring(3,5))-1,
                        Integer.parseInt(ftfDataInicio.getText().substring(0,2)))));
            if (!ftfDataFinal.getText().trim().equals("/  /") || !(ftfDataFinal.getValue() == null))
                        DtF = (new SimpleDateFormat("yyyy-MM-dd").format(new Date(
                        Integer.parseInt(ftfDataFinal.getText().substring(6,10))-1900,
                        Integer.parseInt(ftfDataFinal.getText().substring(3,5))-1,
                        Integer.parseInt(ftfDataFinal.getText().substring(0,2)))));
            if (!(ftfCPFCNPJ.getText().replace("/", "").replace(".", "").replace("-", "").trim().equals("")) ||
                    !(ftfCPFCNPJ.getValue() == null)) Identifi = ftfCPFCNPJ.getText().replace("/", "").replace(".", "").replace("-", "");
            if (cbxObjeto.getSelectedIndex() >= 0) Obj = cbxObjeto.getSelectedItem().toString();
            String Dados [] = {txtReferencia.getText(), Identifi, txtAno.getText(), txtAgencia.getText(), 
                txtRazao.getText(), Obj, DtI, DtF, rbtVigencia.getName(), btaIndeterminado.getName()};
            try {
                vListaContr = vCtrlContratos.ListarComMultiplosFiltros(Dados);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro ao filtrar os dados.\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            }
            atualizarTabela(true);
        }
        vIdFiltro = new Integer[vListaContr.size()];
        for (int i = 0; i < vListaContr.size(); i++) {
            vIdFiltro[i] = vListaContr.get(i).getIdContrato();
        }
        return Ret;
    }
}
