/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import controle.ControleContratos;
import controle.ControleObjetos;
import entidades.Contratos;
import entidades.Objetos;
import java.awt.event.ActionEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import utilidade.Validadores;

/**
 *
 * @author amrsilva
 */
public class informCadContratos extends javax.swing.JInternalFrame {

    /**
     * Creates new form informCadContratos
     */
    public informCadContratos() {
        initComponents();
        try {
            // TODO add your handling code here:
            final MaskFormatter mfAgencia = new MaskFormatter("####");
            ftfAgencia.setFormatterFactory(new DefaultFormatterFactory(mfAgencia));
            final MaskFormatter mfConta = new MaskFormatter("############");
            ftfAno.setFormatterFactory(new DefaultFormatterFactory(mfConta));
            final MaskFormatter mfData = new MaskFormatter("##/##/####");
            ftfAssinatura.setFormatterFactory(new DefaultFormatterFactory(mfData));
            ftfVencimento.setFormatterFactory(new DefaultFormatterFactory(mfData));
            ftfVigencia.setFormatterFactory(new DefaultFormatterFactory(mfData));
            preencherCombo();
        } catch (ParseException ex) {
            Logger.getLogger(informCadContratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void preencherCombo(){
        try {
            cbxObjeto.removeAll();
            DefaultComboBoxModel vModelo = new DefaultComboBoxModel();
            for (Objetos contObj : new ControleObjetos().ListarTodos()){
                vModelo.addElement((Object)contObj.getObjeto());
            }
            cbxObjeto.setModel(vModelo);
            cbxObjeto.setSelectedIndex(-1);
            cbxObjeto.setSelectedItem("");
        } catch (Exception ex) {
            Logger.getLogger(diagObjetos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpCNPJCPF = new javax.swing.ButtonGroup();
        lblReferencia = new javax.swing.JLabel();
        txtReferencia = new javax.swing.JTextField();
        txtRazao = new javax.swing.JTextField();
        lblRazao = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblObjeto = new javax.swing.JLabel();
        lblAgencia = new javax.swing.JLabel();
        lblDataAssinatura = new javax.swing.JLabel();
        lblDataVencimento = new javax.swing.JLabel();
        lblDataVigencia = new javax.swing.JLabel();
        btnAdcionar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        brnFechar = new javax.swing.JButton();
        lblAno = new javax.swing.JLabel();
        rbtCNPJ = new javax.swing.JRadioButton();
        rbtCPF = new javax.swing.JRadioButton();
        ftfCPFCNPJ = new javax.swing.JFormattedTextField();
        ftfAgencia = new javax.swing.JFormattedTextField();
        ftfAno = new javax.swing.JFormattedTextField();
        ftfAssinatura = new javax.swing.JFormattedTextField();
        ftfVencimento = new javax.swing.JFormattedTextField();
        ftfVigencia = new javax.swing.JFormattedTextField();
        btnObjetos = new javax.swing.JButton();
        cbxObjeto = new javax.swing.JComboBox();
        panContas = new javax.swing.JPanel();
        btnContaAd = new javax.swing.JButton();
        btnContaRem = new javax.swing.JButton();
        btnContaAlt = new javax.swing.JButton();
        ftfContaAgencia = new javax.swing.JFormattedTextField();
        ftfContaNumero = new javax.swing.JFormattedTextField();
        txtContaDescricao = new javax.swing.JTextField();
        lblContaAgencia = new javax.swing.JLabel();
        lblContaNumero = new javax.swing.JLabel();
        lblContaDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        panTarifas = new javax.swing.JPanel();
        txtTarifaDescricao = new javax.swing.JTextField();
        lblTarifaDescricao = new javax.swing.JLabel();
        lblTarifaValor = new javax.swing.JLabel();
        ftfTarifaValor = new javax.swing.JFormattedTextField();
        btnTarifaAd = new javax.swing.JButton();
        btnTarifaRem = new javax.swing.JButton();
        btnTarifaAlt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTarifas = new javax.swing.JTable();
        PanAditivos = new javax.swing.JPanel();
        btnAditivoAd = new javax.swing.JButton();
        btnAditivoRem = new javax.swing.JButton();
        btnAditivoAlt = new javax.swing.JButton();
        ftfAditivoNumero = new javax.swing.JFormattedTextField();
        lblAditivoNumero = new javax.swing.JLabel();
        lblAditivoDescricao = new javax.swing.JLabel();
        txtAditivoDescricao = new javax.swing.JTextField();
        lblAditivoAssinatura = new javax.swing.JLabel();
        ftfAditivoAssinatura = new javax.swing.JFormattedTextField();
        spnAditivos = new javax.swing.JScrollPane();
        tblAditivos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de contratos");
        setMinimumSize(new java.awt.Dimension(645, 307));

        lblReferencia.setText("Número");

        lblRazao.setText("Razão Social / Nome");

        lblEndereco.setText("Endereço");

        lblObjeto.setText("Objeto");

        lblAgencia.setText("Agência");

        lblDataAssinatura.setText("Data de Assinatura");

        lblDataVencimento.setText("Data de Vencimento");

        lblDataVigencia.setText("Data de Vigência");

        btnAdcionar.setText("Adcionar Contrato");
        btnAdcionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdcionarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        brnFechar.setText("Fechar");
        brnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnFecharActionPerformed(evt);
            }
        });

        lblAno.setText("Ano");

        bgpCNPJCPF.add(rbtCNPJ);
        rbtCNPJ.setSelected(true);
        rbtCNPJ.setText("CNPJ");
        rbtCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCNPJActionPerformed(evt);
            }
        });

        bgpCNPJCPF.add(rbtCPF);
        rbtCPF.setText("CPF");
        rbtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCPFActionPerformed(evt);
            }
        });

        try {
            ftfCPFCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCPFCNPJ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ftfAgencia.setFocusLostBehavior(3);
        try {
            MaskFormatter mf = new MaskFormatter("####");
            mf.setValueContainsLiteralCharacters(false);
            ftfAgencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mf));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ftfAno.setFocusLostBehavior(3);
        try {
            MaskFormatter mf = new MaskFormatter("yyyy");
            mf.setValueContainsLiteralCharacters(false);
            ftfAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mf));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        ftfAssinatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfAssinatura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ftfVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfVencimento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ftfVigencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfVigencia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnObjetos.setText("+");
        btnObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObjetosActionPerformed(evt);
            }
        });

        panContas.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas"));

        btnContaAd.setText("Adcionar");

        btnContaRem.setText("Remover");

        btnContaAlt.setText("Alterar");

        try {
            ftfAgencia.setFocusLostBehavior(3);
            ftfContaAgencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfAgencia.setFocusLostBehavior(3);
            ftfContaNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblContaAgencia.setText("Agência");

        lblContaNumero.setText("Número");

        lblContaDescricao.setText("Descrição");

        tblContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Agência", "Número"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContas);

        javax.swing.GroupLayout panContasLayout = new javax.swing.GroupLayout(panContas);
        panContas.setLayout(panContasLayout);
        panContasLayout.setHorizontalGroup(
            panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContasLayout.createSequentialGroup()
                .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panContasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContaDescricao)
                            .addGroup(panContasLayout.createSequentialGroup()
                                .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContaAgencia)
                                    .addComponent(ftfContaAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContaNumero)
                                    .addComponent(ftfContaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(196, 196, 196))
                            .addComponent(txtContaDescricao)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panContasLayout.createSequentialGroup()
                        .addComponent(btnContaAd)
                        .addGap(18, 18, 18)
                        .addComponent(btnContaRem)
                        .addGap(18, 18, 18)
                        .addComponent(btnContaAlt)))
                .addContainerGap())
            .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panContasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panContasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnContaAd, btnContaAlt, btnContaRem});

        panContasLayout.setVerticalGroup(
            panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContasLayout.createSequentialGroup()
                .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContaAd)
                    .addComponent(btnContaRem)
                    .addComponent(btnContaAlt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContaDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panContasLayout.createSequentialGroup()
                        .addComponent(lblContaNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfContaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panContasLayout.createSequentialGroup()
                        .addComponent(lblContaAgencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfContaAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panContasLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panContasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnContaAd, btnContaAlt, btnContaRem});

        panTarifas.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarifas"));

        lblTarifaDescricao.setText("Descrição");

        lblTarifaValor.setText("Valor");

        ftfAgencia.setFocusLostBehavior(3);
        ftfTarifaValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        btnTarifaAd.setText("Adcionar");

        btnTarifaRem.setText("Remover");

        btnTarifaAlt.setText("Alterar");

        tblTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Valor (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTarifas);

        javax.swing.GroupLayout panTarifasLayout = new javax.swing.GroupLayout(panTarifas);
        panTarifas.setLayout(panTarifasLayout);
        panTarifasLayout.setHorizontalGroup(
            panTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTarifasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTarifasLayout.createSequentialGroup()
                        .addGroup(panTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTarifaDescricao)
                            .addComponent(txtTarifaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTarifaValor)
                            .addComponent(ftfTarifaValor, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                        .addGap(59, 59, 59))
                    .addGroup(panTarifasLayout.createSequentialGroup()
                        .addComponent(btnTarifaAd)
                        .addGap(18, 18, 18)
                        .addComponent(btnTarifaRem)
                        .addGap(18, 18, 18)
                        .addComponent(btnTarifaAlt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTarifasLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        panTarifasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnTarifaAd, btnTarifaAlt, btnTarifaRem});

        panTarifasLayout.setVerticalGroup(
            panTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTarifasLayout.createSequentialGroup()
                .addGroup(panTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panTarifasLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTarifaValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfTarifaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panTarifasLayout.createSequentialGroup()
                        .addGroup(panTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTarifaAd)
                            .addComponent(btnTarifaRem)
                            .addComponent(btnTarifaAlt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTarifaDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTarifaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panTarifasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnTarifaAd, btnTarifaAlt, btnTarifaRem});

        PanAditivos.setBorder(javax.swing.BorderFactory.createTitledBorder("Aditivos"));

        btnAditivoAd.setText("Adcionar");

        btnAditivoRem.setText("Remover");

        btnAditivoAlt.setText("Alterar");

        ftfAditivoNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###"))));
        ftfAditivoNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfAditivoNumeroFocusLost(evt);
            }
        });

        lblAditivoNumero.setText("Nº");

        lblAditivoDescricao.setText("Descrição");

        lblAditivoAssinatura.setText("Data da Assinatura");

        ftfAditivoAssinatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        ftfAditivoAssinatura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        spnAditivos.setBorder(null);

        tblAditivos.setBorder(null);
        tblAditivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Descrição", "Assinatura"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAditivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spnAditivos.setViewportView(tblAditivos);

        javax.swing.GroupLayout PanAditivosLayout = new javax.swing.GroupLayout(PanAditivos);
        PanAditivos.setLayout(PanAditivosLayout);
        PanAditivosLayout.setHorizontalGroup(
            PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanAditivosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnAditivos)
                    .addGroup(PanAditivosLayout.createSequentialGroup()
                        .addComponent(btnAditivoAd)
                        .addGap(18, 18, 18)
                        .addComponent(btnAditivoRem)
                        .addGap(18, 18, 18)
                        .addComponent(btnAditivoAlt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanAditivosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfAditivoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAditivoNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAditivoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAditivoDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAditivoAssinatura)
                    .addComponent(ftfAditivoAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        PanAditivosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAditivoAd, btnAditivoAlt, btnAditivoRem});

        PanAditivosLayout.setVerticalGroup(
            PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanAditivosLayout.createSequentialGroup()
                .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAditivoAd)
                    .addComponent(btnAditivoRem)
                    .addComponent(btnAditivoAlt))
                .addGap(18, 18, 18)
                .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanAditivosLayout.createSequentialGroup()
                        .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAditivoNumero)
                            .addComponent(lblAditivoDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanAditivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfAditivoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAditivoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanAditivosLayout.createSequentialGroup()
                        .addComponent(lblAditivoAssinatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfAditivoAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(spnAditivos, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );

        PanAditivosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAditivoAd, btnAditivoAlt, btnAditivoRem});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReferencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRazao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRazao)
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panTarifas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtCNPJ)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtCPF))
                                    .addComponent(ftfCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblObjeto)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbxObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnObjetos)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgencia)
                                    .addComponent(ftfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEndereco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataAssinatura)
                                    .addComponent(ftfAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataVencimento)
                                    .addComponent(ftfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataVigencia)
                                    .addComponent(ftfVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(478, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanAditivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdcionar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEndereco)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {brnFechar, btnAdcionar, btnLimpar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panContas, panTarifas});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReferencia)
                    .addComponent(lblRazao)
                    .addComponent(lblAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgencia)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtCNPJ)
                            .addComponent(rbtCPF)
                            .addComponent(lblObjeto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftfCPFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnObjetos)
                            .addComponent(cbxObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataVigencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDataAssinatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfAssinatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panTarifas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanAditivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdcionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(brnFechar)
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdcionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdcionarActionPerformed
        // TODO add your handling code here:
        String vCPFCNPJ;
        if (rbtCNPJ.isSelected()) {
            if (ftfCPFCNPJ.getText().replace(".", "").replace("-", "").replace("/", "").trim().equals("")){
                vCPFCNPJ = null;
            } else {
                vCPFCNPJ = ftfCPFCNPJ.getText().replace(".", "").replace("-", "").replace("/", "");
                vCPFCNPJ = "00000000000000".substring(vCPFCNPJ.length()) + vCPFCNPJ;
                if (!Validadores.isCNPJ(vCPFCNPJ)) {
                    JOptionPane.showMessageDialog(btnAdcionar, "CNPJ inválido");
                    return;
                }
            }
        } else {
            if (ftfCPFCNPJ.getText().replace(".", "").replace("-", "").replace("/", "").trim().equals("")){
                vCPFCNPJ = null;
            } else {
                vCPFCNPJ = ftfCPFCNPJ.getText().replace(".", "").replace("-", "").replace("/", "");
                vCPFCNPJ = "00000000000".substring(vCPFCNPJ.length()) + vCPFCNPJ;
                if (!Validadores.isCPF(vCPFCNPJ)) {
                    JOptionPane.showMessageDialog(btnAdcionar, "CPF inválido");
                    return;
                }
            }
        }
        Contratos vContrato = new Contratos();
        vContrato.setReferencia(Integer.parseInt(txtReferencia.getText()));
        vContrato.setAgencia(Integer.parseInt(ftfAgencia.getText().trim()));
        vContrato.setIdentificador(vCPFCNPJ);
        vContrato.setObjeto(cbxObjeto.getSelectedItem().toString());
        vContrato.setEndereco(txtEndereco.getText());
        vContrato.setRazao(txtRazao.getText());
        try {
            if (!ftfAno.getText().equals("    ")) vContrato.setAno(Integer.parseInt(ftfAno.getText().trim()));
            if (!ftfAssinatura.getText().equals("  /  /    ")) vContrato.setAssinatura(new SimpleDateFormat("dd/MM/yyyy").parse(
                    ftfAssinatura.getText()));
            if (!ftfVigencia.getText().equals("  /  /    ")) vContrato.setVigencia(new SimpleDateFormat("dd/MM/yyyy").parse(
                    ftfVigencia.getText()));
            if (!ftfVencimento.getText().equals("  /  /    ")) vContrato.setVencimento(new SimpleDateFormat("dd/MM/yyyy").parse(
                    ftfVencimento.getText()));
            new ControleContratos().Incluir(vContrato);
            this.btnLimparActionPerformed(new ActionEvent(btnAdcionar, 0, ""));
            JOptionPane.showMessageDialog(this, "Contrato cadastrado com sucesso.","Incluir", JOptionPane.INFORMATION_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this,"Verifique o campo Data de assinatura\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,"Verifique o campo Ano\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(this,"Já existe um contrato com esse número nesse ano\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            }
            Logger.getLogger(informCadContratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdcionarActionPerformed

    private void brnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_brnFecharActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtEndereco.setText("");
        cbxObjeto.setSelectedIndex(-1);
        txtRazao.setText("");
        txtReferencia.setText("");
        ftfAgencia.setText("");
        ftfAno.setText("");
        ftfCPFCNPJ.setText("");
        ftfAssinatura.setText("");
        ftfVencimento.setText("");
        ftfVigencia.setText("");
        ftfAssinatura.setValue(null);
        ftfVencimento.setValue(null);
        ftfVigencia.setValue(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void rbtCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCNPJActionPerformed
        try {
            // TODO add your handling code here:
            final MaskFormatter mfCNPJ = new MaskFormatter("##.###.###/####-##");
            ftfCPFCNPJ.setText("");
            ftfCPFCNPJ.setValue(null);
            if (evt.getActionCommand().equals("CNPJ")){
                ftfCPFCNPJ.setFormatterFactory(new DefaultFormatterFactory(mfCNPJ));
            }
        } catch (ParseException ex) {
            Logger.getLogger(informCadContratos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_rbtCNPJActionPerformed

    private void rbtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCPFActionPerformed
        try {
            // TODO add your handling code here:
            final MaskFormatter mfCPF = new MaskFormatter("###.###.###-##");
            ftfCPFCNPJ.setText("");
            ftfCPFCNPJ.setValue(null);
            if (evt.getActionCommand().equals("CPF")){
                ftfCPFCNPJ.setFormatterFactory(new DefaultFormatterFactory(mfCPF));
            }
        } catch (ParseException ex) {
            Logger.getLogger(informCadContratos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbtCPFActionPerformed

    private void btnObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObjetosActionPerformed
        // TODO add your handling code here:
        new diagObjetos(null, true, this).setVisible(true);
    }//GEN-LAST:event_btnObjetosActionPerformed

    private void ftfAditivoNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfAditivoNumeroFocusLost
        // TODO add your handling code here:
        if (ftfAditivoNumero.getText().equals("")) ftfAditivoNumero.setValue(null);
    }//GEN-LAST:event_ftfAditivoNumeroFocusLost
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanAditivos;
    private javax.swing.ButtonGroup bgpCNPJCPF;
    private javax.swing.JButton brnFechar;
    private javax.swing.JButton btnAdcionar;
    private javax.swing.JButton btnAditivoAd;
    private javax.swing.JButton btnAditivoAlt;
    private javax.swing.JButton btnAditivoRem;
    private javax.swing.JButton btnContaAd;
    private javax.swing.JButton btnContaAlt;
    private javax.swing.JButton btnContaRem;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnObjetos;
    private javax.swing.JButton btnTarifaAd;
    private javax.swing.JButton btnTarifaAlt;
    private javax.swing.JButton btnTarifaRem;
    private javax.swing.JComboBox<String> cbxObjeto;
    private javax.swing.JFormattedTextField ftfAditivoAssinatura;
    private javax.swing.JFormattedTextField ftfAditivoNumero;
    private javax.swing.JFormattedTextField ftfAgencia;
    private javax.swing.JFormattedTextField ftfAno;
    private javax.swing.JFormattedTextField ftfAssinatura;
    private javax.swing.JFormattedTextField ftfCPFCNPJ;
    private javax.swing.JFormattedTextField ftfContaAgencia;
    private javax.swing.JFormattedTextField ftfContaNumero;
    private javax.swing.JFormattedTextField ftfTarifaValor;
    private javax.swing.JFormattedTextField ftfVencimento;
    private javax.swing.JFormattedTextField ftfVigencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAditivoAssinatura;
    private javax.swing.JLabel lblAditivoDescricao;
    private javax.swing.JLabel lblAditivoNumero;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblContaAgencia;
    private javax.swing.JLabel lblContaDescricao;
    private javax.swing.JLabel lblContaNumero;
    private javax.swing.JLabel lblDataAssinatura;
    private javax.swing.JLabel lblDataVencimento;
    private javax.swing.JLabel lblDataVigencia;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblObjeto;
    private javax.swing.JLabel lblRazao;
    private javax.swing.JLabel lblReferencia;
    private javax.swing.JLabel lblTarifaDescricao;
    private javax.swing.JLabel lblTarifaValor;
    private javax.swing.JPanel panContas;
    private javax.swing.JPanel panTarifas;
    private javax.swing.JRadioButton rbtCNPJ;
    private javax.swing.JRadioButton rbtCPF;
    private javax.swing.JScrollPane spnAditivos;
    private javax.swing.JTable tblAditivos;
    private javax.swing.JTable tblContas;
    private javax.swing.JTable tblTarifas;
    private javax.swing.JTextField txtAditivoDescricao;
    private javax.swing.JTextField txtContaDescricao;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JTextField txtReferencia;
    private javax.swing.JTextField txtTarifaDescricao;
    // End of variables declaration//GEN-END:variables
}
